[config]
schemaVersion = "0.0.1"

[package]
namespace = "hunkyburrito"
name = "NoRoll"
description = "Disables roll animation"
websiteUrl = "https://github.com/hunkyburrito/MycopunkNoRoll"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/NoRoll.dll"
target = "BepInEx/plugins/NoRoll.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


